# Site settings
title: Sidmouth Senior Care
description: "Care for seniors in Sidmouth, Devon, UK."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.png

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Sidmouth Senior Care
    hero_description: Care for seniors in Sidmouth, Devon, UK

# Contact form
api_token: b75bef6e344301063f829278885dde34

# Contact info
contact:
    phone: 07411 104 1212
    email: helen@sidmouthseniorcare.co.uk
    address: 1 Fortfield Terrace, <br> Sidmouth, Devon, United Kingdom

# Opening hours
monday_friday: 8:00 – 18:00
saturday: 8:00 – 17:00
sunday: 8:00 – 17:00

# Testimonials
testimonials:
    testimonials_img: parallax.jpg

# Map
map:
    zoom: 17
    address: 1 Fortfield Terrace, Sidmouth, Devon, United Kingdom
    address_details: svg/min/logo.svg

# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
feed: yes

# Footer
copyright: © 2017 Sidmouth Senior Care - All rights reserved

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: UA-83022405-1
google_verification:
